### ISSUE TITLE
Add project description in readme.md

### ISSUE THREAD

**Issue by anhquan99** [anhquan99/khong_biet_dictionary#9]

**Comment by anhquan99** [comment]
Hi @vidikun, I need you to add the project description to readme.md file. You can write what is the main idea about. By doing this you need to learn about markdown, just simple no need to be advanced.

**Comment by vidikun** [comment]
Task done. Please give new task @anhquan99 .

**Comment by anhquan99** [comment]
Hi @vidikun,please translate the description into English and the home page in wiki too.

**Comment by anhquan99** [comment]
Thanks @vidikun for the update
